const express = require('express');
const adminController = require('../controllers/adminController');
const sponsorshipOpsController = require('../controllers/sponsorshipOpsController');
const { requireAdmin } = require('../middleware/authMiddleware');
const mediaRoutes = require('./mediaRoutes');

const router = express.Router();

router.use(requireAdmin);
router.use('/media', mediaRoutes);
router.get('/', adminController.index);
router.get('/users', adminController.users);
router.get('/donations', adminController.donations);
router.get('/donations/export.csv', adminController.exportDonationsCsv);
router.get('/donations/:id', adminController.viewDonation);
router.get('/donations/:id/receipt', adminController.viewDonationReceipt);
router.post('/donations/:id/verify', adminController.verifyDonation);
router.post('/donations/:id/reject', adminController.rejectDonation);
router.post('/donations/:id/cancel', adminController.cancelDonation);
router.post('/donations/manual', adminController.createManualDonation);
router.get('/sponsorships', adminController.sponsorships);
router.get('/sponsorships/export.csv', adminController.exportSponsorshipsCsv);
router.get('/sponsorships/:id', adminController.viewSponsorship);
router.post('/sponsorships/:id/contacted', adminController.markSponsorshipContacted);
router.post('/sponsorships/:id/approve', adminController.approveSponsorship);
router.post('/sponsorships/:id/reject', adminController.rejectSponsorship);
router.post('/sponsorships/:id/archive', adminController.archiveSponsorship);
router.post('/sponsorships/:id/note', adminController.addSponsorshipNote);
router.get('/children', sponsorshipOpsController.children);
router.get('/children/create', sponsorshipOpsController.newChild);
router.post('/children', sponsorshipOpsController.createChild);
router.get('/children/:id/edit', sponsorshipOpsController.editChild);
router.post('/children/:id', sponsorshipOpsController.updateChild);
router.post('/children/:id/archive', sponsorshipOpsController.archiveChild);
router.post('/children/:id/updates', sponsorshipOpsController.createChildUpdate);
router.post('/children/:id/updates/:updateId', sponsorshipOpsController.updateChildUpdate);
router.post('/children/:id/updates/:updateId/archive', sponsorshipOpsController.archiveChildUpdate);
router.get('/sponsorship-projects', sponsorshipOpsController.sponsorshipProjects);
router.get('/sponsorship-projects/create', sponsorshipOpsController.newSponsorshipProject);
router.post('/sponsorship-projects', sponsorshipOpsController.createSponsorshipProject);
router.get('/sponsorship-projects/:id/edit', sponsorshipOpsController.editSponsorshipProject);
router.post('/sponsorship-projects/:id', sponsorshipOpsController.updateSponsorshipProject);
router.post('/sponsorship-projects/:id/archive', sponsorshipOpsController.archiveSponsorshipProject);
router.post('/sponsorship-projects/:id/updates', sponsorshipOpsController.createProjectUpdate);
router.post('/sponsorship-projects/:id/updates/:updateId', sponsorshipOpsController.updateProjectUpdate);
router.post('/sponsorship-projects/:id/updates/:updateId/archive', sponsorshipOpsController.archiveProjectUpdate);
router.get('/mission-workers', sponsorshipOpsController.missionWorkers);
router.get('/mission-workers/create', sponsorshipOpsController.newMissionWorker);
router.post('/mission-workers', sponsorshipOpsController.createMissionWorker);
router.get('/mission-workers/:id/edit', sponsorshipOpsController.editMissionWorker);
router.post('/mission-workers/:id', sponsorshipOpsController.updateMissionWorker);
router.post('/mission-workers/:id/archive', sponsorshipOpsController.archiveMissionWorker);
router.post('/mission-workers/:id/updates', sponsorshipOpsController.createMissionWorkerUpdate);
router.post('/mission-workers/:id/updates/:updateId', sponsorshipOpsController.updateMissionWorkerUpdate);
router.post('/mission-workers/:id/updates/:updateId/archive', sponsorshipOpsController.archiveMissionWorkerUpdate);
router.get('/sponsorship-assignments', sponsorshipOpsController.sponsorshipAssignments);
router.get('/sponsorship-assignments/create', sponsorshipOpsController.newSponsorshipAssignment);
router.post('/sponsorship-assignments', sponsorshipOpsController.createSponsorshipAssignment);
router.get('/sponsorship-assignments/:id', sponsorshipOpsController.viewSponsorshipAssignment);
router.post('/sponsorship-assignments/:id/status', sponsorshipOpsController.updateSponsorshipAssignmentStatus);
router.get('/volunteers', adminController.volunteers);
router.get('/volunteers/export.csv', adminController.exportVolunteersCsv);
router.get('/volunteers/:id', adminController.viewVolunteer);
router.post('/volunteers/:id/reviewing', adminController.markVolunteerReviewing);
router.post('/volunteers/:id/approve', adminController.approveVolunteer);
router.post('/volunteers/:id/reject', adminController.rejectVolunteer);
router.post('/volunteers/:id/archive', adminController.archiveVolunteer);
router.post('/volunteers/:id/note', adminController.addVolunteerNote);
router.get('/prayer', adminController.prayer);
router.get('/prayer/partners/export.csv', adminController.exportPrayerPartnersCsv);
router.get('/prayer/requests/export.csv', adminController.exportPrayerRequestsCsv);
router.get('/prayer/requests/:id', adminController.viewPrayerRequest);
router.post('/prayer/partners/:id/status', adminController.updatePrayerPartnerStatus);
router.post('/prayer/requests/:id/status', adminController.updatePrayerRequestStatus);
router.post('/prayer/requests/:id/archive', adminController.archivePrayerRequest);
router.post('/prayer/requests/:id/note', adminController.addPrayerRequestNote);
router.get('/blog-posts', adminController.blogPosts);
router.get('/blog-posts/new', adminController.newBlogPost);
router.post('/blog-posts', adminController.createBlogPost);
router.get('/blog-posts/:id/edit', adminController.editBlogPost);
router.post('/blog-posts/:id', adminController.updateBlogPost);
router.post('/blog-posts/:id/status', adminController.updateBlogPostStatus);
router.get('/projects', adminController.projects);
router.get('/projects/new', adminController.newProject);
router.post('/projects', adminController.createProject);
router.get('/projects/:id/edit', adminController.editProject);
router.post('/projects/:id', adminController.updateProject);
router.post('/projects/:id/status', adminController.updateProjectStatus);
router.get('/messages', adminController.messages);
router.get('/messages/:id', adminController.viewMessage);
router.post('/messages/:id/status', adminController.updateMessageStatus);
router.get('/gallery', adminController.gallery);
router.get('/gallery/create', adminController.newGalleryItem);
router.post('/gallery', adminController.createGalleryItem);
router.get('/gallery/:id/edit', adminController.editGalleryItem);
router.post('/gallery/:id', adminController.updateGalleryItem);
router.post('/gallery/:id/archive', adminController.archiveGalleryItem);
router.post('/gallery/:id/delete', adminController.deleteGalleryItem);
router.get('/testimonies', adminController.testimonies);
router.get('/testimonies/create', adminController.newTestimony);
router.post('/testimonies', adminController.createTestimony);
router.get('/testimonies/:id/edit', adminController.editTestimony);
router.post('/testimonies/:id', adminController.updateTestimony);
router.post('/testimonies/:id/archive', adminController.archiveTestimony);
router.post('/testimonies/:id/feature', adminController.toggleFeaturedTestimony);
router.get('/pages', adminController.pages);
router.get('/pages/create', adminController.newPage);
router.post('/pages', adminController.createPage);
router.get('/pages/:id/edit', adminController.editPage);
router.post('/pages/:id', adminController.updatePage);
router.post('/pages/:id/archive', adminController.archivePage);
router.get('/homepage-content', adminController.homepageContent);
router.get('/homepage-content/:id/edit', adminController.editHomepageSection);
router.post('/homepage-content/:id', adminController.updateHomepageSection);
router.post('/homepage-content/:id/toggle', adminController.toggleHomepageSection);
router.get('/email-templates', adminController.emailTemplates);
router.get('/email-templates/:id/edit', adminController.editEmailTemplate);
router.post('/email-templates/:id', adminController.updateEmailTemplate);
router.get('/notification-logs', adminController.notificationLogs);
router.get('/settings', adminController.settings);
router.post('/settings', adminController.updateSettings);
router.post('/settings/test-email', adminController.sendTestEmail);
router.get('/audit-logs', adminController.auditLogs);
router.get('/audit-logs/:id', adminController.viewAuditLog);
router.get('/demo-notes', adminController.demoNotes);

module.exports = router;

